name: go test

on:
  workflow_call:
jobs:
  go_test:
    name: go test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: go test
        run: go test

